name: Build and Deploy
on:
  push:
    branches:
      - main  # replace with your default branch if not 'main'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          npm run deploy